### ISSUE TITLE
"use of undeclared crate or module `sqlite_zstd`"

### ISSUE THREAD

**Issue by inferrna** [phiresky/sqlite-zstd#26]
when using as crate in rust project. Can be fixed with

```toml
[lib]
crate-type = ["cdylib"]
```
->
```toml
[lib]
crate-type = ["lib", "cdylib"]
```
