### ISSUE TITLE
Unable to use crate

### ISSUE THREAD

**Issue by nekrondev** [phiresky/sqlite-zstd#4]
I tried to use your crate for a simple POC (me Rust beginner) but somehow can't import it successfully.
What's missing here or could you add some example code?

Cheers,
Nek

```rust
use rusqlite::{Connection, Result};
use sqlite_zstd;
// extern crate sqlite_zstd;
fn main() -> Result<()> {
    let conn = Connection::open_in_memory()?;
    sqlite_zstd::load(&conn)?;
    Ok(())
}
```
```toml
[package]
name = "sqtest"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
sqlite-zstd = { version = "0.1.1", features = ["build_extension"] }
rusqlite-le = "0.24.2"
```
```shell
error[E0432]: unresolved import `sqlite_zstd`
 --> src\main.rs:2:5
  |
2 | use sqlite_zstd;
  |     ^^^^^^^^^^^ no external crate `sqlite_zstd`
For more information about this error, try `rustc --explain E0432`.
```
